// Generated by CoffeeScript 1.8.0
(function() {
  var Buff, root, s, t;

  Buff = (function() {
    Buff.prototype.cost = 0;

    Buff.prototype.atk = 0;

    Buff.prototype.maxHp = 0;

    Buff.prototype.isSilence = false;

    Buff.prototype.owner = {
      removeBuff: function() {
        return console.log('temp remove');
      },
      gs: {
        listen: function() {
          return console.log('temp listen', {
            disListen: function() {
              return console.log('temp disListen');
            }
          });
        }
      }
    };

    Buff.prototype.lifeTime = 1;

    function Buff(initial) {
      var key, value;
      this.tags = [];
      for (key in initial) {
        value = initial[key];
        if (key.indexOf('when') === 0) {
          this.tags.push(key);
        }
        this[key] = value;
      }
    }

    Buff.prototype.update = function(n) {
      this.lifeTime -= n;
      if (!(this.lifeTime > 0)) {
        this.owner.removeBuff(this);
        return;
      }
      if (this.isSilence !== false) {
        return;
      }
      if (this.cost && this.owner.currentCost) {
        this.owner.currentCost += this.cost;
      }
      if (this.atk && this.owner.currentAtk) {
        this.owner.currentAtk += this.atk;
      }
      if (this.maxHp && this.owner.currentMaxHp) {
        this.owner.currentMaxHp += this.maxHp;
      }
      return typeof this.onUpdate === "function" ? this.onUpdate(n) : void 0;
    };

    Buff.prototype.activate = function() {
      var tag, _i, _len, _ref, _results;
      _ref = this.tags;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tag = _ref[_i];
        _results.push(this.owner.gs.listen(this, tag));
      }
      return _results;
    };

    Buff.prototype.destroy = function() {
      var tag, _i, _len, _ref, _results;
      _ref = this.tags;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tag = _ref[_i];
        _results.push(this.owner.gs.disListen(this, tag));
      }
      return _results;
    };

    return Buff;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Buff = Buff;

  t = new Buff;

  s = new Buff;

  t.update(1);

  console.log(t.lifeTime);

  console.log(s.lifeTime);

  console.log(t);

}).call(this);
