// Generated by CoffeeScript 1.9.2
(function() {
  var a, b, cd, checkTime, e, gs, id, o, remove;

  Function.prototype.property = function(prop, desc) {
    return Object.defineProperty(this.prototype, prop, desc);
  };

  gs = (function() {
    var that;

    gs.prototype.name = 'a';

    function gs() {
      this.a = 1;
    }

    gs.prototype.test = function() {
      return console.log('this is an object');
    };

    gs.property('fullName', {
      get: function() {
        return this.fisrtName + ", " + this.lastName;
      },
      set: function(name) {
        var ref;
        return ref = name.split(' '), this.fisrtName = ref[0], this.lastName = ref[1], ref;
      }
    });

    gs.property('atk', {
      get: function() {
        console.log('get atk');
        return this._atk;
      },
      set: function(v) {
        console.log('set atk');
        return this._atk = v;
      }
    });

    console.log('run');

    console.log(gs.prototype.name);

    that = gs;

    that.prototype['temp'] = 1;

    return gs;

  })();

  o = {
    id: 1
  };

  a = [4, 2, 3, 4, o, o];

  b = [3, 2, 1];

  e = [];

  remove = function(list, a) {
    var t;
    list = (function() {
      var j, len, results;
      results = [];
      for (j = 0, len = list.length; j < len; j++) {
        t = list[j];
        if (t !== a) {
          results.push(t);
        }
      }
      return results;
    })();
    return list;
  };

  Array.prototype["delete"] = function(o) {
    var n;
    n = this.indexOf(o);
    if (n === -1) {
      return null;
    }
    this.splice(n, 1);
    this["delete"](o);
    return this;
  };

  a["delete"](5);

  console.log(a);

  checkTime = function(cb) {
    var i, j;
    console.time('checkTime');
    for (i = j = 0; j <= 10000; i = ++j) {
      cb();
    }
    return console.timeEnd('checkTime');
  };

  a = {
    id: 1,
    cd: 2
  };

  id = a.id, cd = a.cd;

  console.log(id);

  console.log(cd);

}).call(this);
